# Generated by Django 6.0.3.0 on 2026-04-16-12:24

from django.db import migrations, models


class Migration(migrations.Migrations):
 
  initail = True

dependencies = [
]

operations = [
  migrations.CreateModel(
    name='WeeklyLog',
    fields=[
      ('id', models.BigAutoField(auto_create=True, primary_key=True, serializer=False, verbose_name='ID')),
      ('week_number', models.IntegerField()),
      ('content', models.TextField()),
      ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted',' Submitted'),('reviewed',' Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
      ('created_at', models.DateField(auto_now_add=True)),
    ],
  ),
  


