# Generated by Django 6.03.0 on 2026-04-16-12:15
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



class Migration(migration.Migration):
  
  initial = TRUE

dependencies = [
  ('logs', '0001_initials'),
  migrations.swappable_dependency(settings.AUTH_USER_MODEL),
]



