# Generated by Django 6.0.5 on 2026-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('log_submitted', 'Log Submitted'), ('log_approved', 'Log Approved'), ('log_rejected', 'Log Rejected'), ('evaluation_created', 'Evaluation Created'), ('placement_assigned', 'Placement Assigned')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
