# Generated by Django 6.0.3 on 2026-04-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
