# Generated by Django 6.0.5 on 2026-05-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipplacement',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
