# Generated by Django 6.0.4 on 2026-04-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipplacement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
